---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Navigations
- type: document
  path: _data/nav-primary.yml
  label: Header Primary Nav
- type: document
  path: _data/footer-nav.yml
  label: Footer Nav
- type: heading
  label: Pages
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: Other
- type: directory
  path: _social-links
  label: Social Links
  create: all
  match: "**/*"
- type: document
  path: _data/policy-links.yml
  label: Policy Links
- type: document
  path: _data/certificates.yml
  label: Certificates
upload_dir: assets/images
public_path: assets/images
front_matter_path: assets/images
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
