---
title: Personalized Onboarding and Training
training_cards:
- icon: assets/images/icon-training2.svg
  description: Advanced topics, data governance trainings, 1:1 working sessions on
    your data
- icon: assets/images/icon-training1.svg
  description: Live Trainings Customized Specifically to You and Your Data
training_table: []
