---
title: Personalized Onboarding and Training
training_cards:
- icon: assets/images/icon-training2.svg
  description: Advanced topics, data governance trainings, 1:1 working sessions on
    your data
- icon: assets/images/icon-training1.svg
  description: Live Trainings Customized Specifically to You and Your Data
training_table:
- title: Iteration
  content: |-
    * V3 Reporting Scoping and Training
    * QA of Data Pipeline

    ***

    * Ongoing Consultations and Best Practice Sharing
- title: Deploy & Training
  content: |-
    * Implement V2 of Reports
    * Deep-dive Training
    * Implementation Sign-off
    * Customer Satisfaction QA Checkpoint of Data Pipeline
- title: Setup
  content: |-
    * V1 Charts Setup for Primary Use Cases and Best Practices
    * V1 Product Training
    * V2 Spec Reporting Requirements
- title: Planning
  content: |-
    * Project Kick-off Meeting
    * Project Work Plan
    * Team Organization
    * V1 Scope
